// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Detecta el tempo (BPM) de un archivo de audio analizando su contenido.
///
/// Usa la envolvente de energía (RMS por ventanas cortas), obtiene la señal
/// de onset (incrementos de energía) y busca el período dominante por
/// autocorrelación dentro del rango 60-200 BPM. El resultado se pliega al
/// rango 70-180 BPM.
/// Devuelve `None` si el archivo no se pudo decodificar o es demasiado corto.
Future<int?> detectBpm({required String path}) =>
    RustLib.instance.api.crateApiBpmDetectBpm(path: path);
