// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `compute_spectral_bands_range`, `fft_radix2`, `simple_fft_bands`

/// Decodifica el audio a mono y calcula el RMS por ventanas de [`HOP`].
///
/// Con `max_seconds = Some(s)` corta el análisis a los primeros `s` segundos;
/// con `None` analiza el archivo completo. El audio nunca se acumula entero
/// en memoria: solo la envolvente.
Future<Envelope?> computeEnvelope({required String path, double? maxSeconds}) =>
    RustLib.instance.api.crateApiEnergyComputeEnvelope(
      path: path,
      maxSeconds: maxSeconds,
    );

/// Analiza la energía de todo el archivo: RMS por ventana, normalizado 0–1.
///
/// De esta envolvente se derivan la forma de onda y el visualizador de
/// golpes reales de la app. El resultado se cachea del lado de Dart.
Future<EnergyAnalysis?> analyzeEnergy({required String path}) =>
    RustLib.instance.api.crateApiEnergyAnalyzeEnergy(path: path);

/// Análisis espectral completo: extrae bandas de frecuencia.
Future<SpectralAnalysis?> analyzeSpectral({required String path}) =>
    RustLib.instance.api.crateApiEnergyAnalyzeSpectral(path: path);

/// Analiza solo el fragmento [start_seconds, start_seconds + duration_seconds]
/// del archivo y devuelve sus bandas de frecuencia.
///
/// Pensado para el análisis progresivo del lado Dart: se encadenan llamadas
/// avanzando `start_seconds`, se actualiza el visualizador en vivo con cada
/// fragmento y el resultado completo se cachea al terminar.
Future<SpectralAnalysis?> analyzeSpectralChunk({
  required String path,
  required double startSeconds,
  required double durationSeconds,
}) => RustLib.instance.api.crateApiEnergyAnalyzeSpectralChunk(
  path: path,
  startSeconds: startSeconds,
  durationSeconds: durationSeconds,
);

/// Resultado del análisis de energía, listo para la UI.
class EnergyAnalysis {
  /// Energía RMS por ventana, normalizada 0–1.
  final Float32List windows;

  /// Ventanas por segundo (depende del sample rate del archivo).
  final double windowsPerSecond;

  const EnergyAnalysis({required this.windows, required this.windowsPerSecond});

  @override
  int get hashCode => windows.hashCode ^ windowsPerSecond.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnergyAnalysis &&
          runtimeType == other.runtimeType &&
          windows == other.windows &&
          windowsPerSecond == other.windowsPerSecond;
}

/// Envolvente de energía: RMS por ventana junto al sample rate del archivo.
class Envelope {
  final Float32List windows;
  final BigInt sampleRate;

  const Envelope({required this.windows, required this.sampleRate});

  @override
  int get hashCode => windows.hashCode ^ sampleRate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Envelope &&
          runtimeType == other.runtimeType &&
          windows == other.windows &&
          sampleRate == other.sampleRate;
}

/// Análisis espectral: bandas de frecuencia por ventana.
class SpectralAnalysis {
  /// Energía normalizada 0–1 por banda (frecuencia) y por ventana.
  /// Disposición: [banda_0_ventana_0, banda_1_ventana_0, ..., banda_0_ventana_1, ...].
  final Float32List bands;

  /// Número de bandas espectrales.
  final int numBands;

  /// Ventanas por segundo.
  final double windowsPerSecond;

  const SpectralAnalysis({
    required this.bands,
    required this.numBands,
    required this.windowsPerSecond,
  });

  @override
  int get hashCode =>
      bands.hashCode ^ numBands.hashCode ^ windowsPerSecond.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpectralAnalysis &&
          runtimeType == other.runtimeType &&
          bands == other.bands &&
          numBands == other.numBands &&
          windowsPerSecond == other.windowsPerSecond;
}
